
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'maison_h'
version: '1.0.0'
config-version: 2

models:
  maison_h:
    staging:
      +materialized: view
      # +schema: staging
    intermediate:
      +materialized: table # Couche Silver
      # +schema: intermediate
    marts:
      +materialized: table
      # +schema: marts


vars:
  # Seuils de segmentation pour la Maison H
  client_threshold: 2000
  top_client_threshold: 10000
  vic_threshold: 50000